#ifndef __SYS_CONFIG_M0_H
#define __SYS_CONFIG_M0_H

#include "main.h"

#define NVIC_IRQ_PRIO_0							0
#define NVIC_IRQ_PRIO_HALL						NVIC_IRQ_PRIO_0

#define NVIC_IRQ_PRIO_1							(NVIC_IRQ_PRIO_0 + 1)
#define NVIC_IRQ_PRIO_TIM_PWM	                NVIC_IRQ_PRIO_1
#define NVIC_IRQ_PRIO_DMA_SENS_HIGH_FREQ	    NVIC_IRQ_PRIO_1

#define NVIC_IRQ_PRIO_2							(NVIC_IRQ_PRIO_1 + 1)
#define NVIC_IRQ_PRIO_TIM_SPEED_CONTROL	        NVIC_IRQ_PRIO_2

#define NVIC_IRQ_PRIO_3							(NVIC_IRQ_PRIO_2 + 1)
#define NVIC_IRQ_PRIO_TIMER_HALL_TOGGLE	        NVIC_IRQ_PRIO_3

#define NVIC_IRQ_PRIO_4							(NVIC_IRQ_PRIO_3 + 1)
#define NVIC_IRQ_PRIO_USART_RX			        (NVIC_IRQ_PRIO_4)

#define NVIC_IRQ_PRIO_5							(NVIC_IRQ_PRIO_4 + 1)
#define NVIC_IRQ_PRIO_USART_DEBUG_DMA_RX        (NVIC_IRQ_PRIO_5)
#define NVIC_IRQ_PRIO_USART_DEBUG_DMA_TX        (NVIC_IRQ_PRIO_5)

#define NVIC_IRQ_PRIO_6							(NVIC_IRQ_PRIO_5 + 1)
#define NVIC_IRQ_PRIO_DMA_SENS_LOW_FREQ	        (NVIC_IRQ_PRIO_6)

#define NVIC_IRQ_PRIO_7							(NVIC_IRQ_PRIO_6 + 1)
#define NVIC_IRQ_PRIO_TIM_DELAY					NVIC_IRQ_PRIO_7

#define NVIC_IRQ_PRIO_8							(NVIC_IRQ_PRIO_7 + 1)
#define NVIC_IRQ_PRIO_9							(NVIC_IRQ_PRIO_8 + 1)
#define NVIC_IRQ_PRIO_10						(NVIC_IRQ_PRIO_9 + 1)
#define NVIC_IRQ_PRIO_11						(NVIC_IRQ_PRIO_10 + 1)
#define NVIC_IRQ_PRIO_12						(NVIC_IRQ_PRIO_11 + 1)
#define NVIC_IRQ_PRIO_13						(NVIC_IRQ_PRIO_12 + 1)
#define NVIC_IRQ_PRIO_14						(NVIC_IRQ_PRIO_13 + 1)

#endif /* __SYS_CONFIG_M0_H */
