#ifndef __TASKS_STACK_AND_PRIORITY_H
#define __TASKS_STACK_AND_PRIORITY_H

/*
 * Priority
 */
#define MOTOR_CONTROL_TASK_PRIORITY			0 + tskIDLE_PRIORITY
#define SENSORS_CONTROL_TASK_PRIORITY		1 + tskIDLE_PRIORITY
#define MOTOR_UART_PROCESS_RX_TASK_PRIORITY 4 + tskIDLE_PRIORITY
#define MOTOR_UART_PROCESS_TX_TASK_PRIORITY 5 + tskIDLE_PRIORITY
#define DEBUG_PROCESS_TASK_PRIORITY			6 + tskIDLE_PRIORITY
#define WATCHDOG_TASK_PRIORITY				7 + tskIDLE_PRIORITY

/*
 * Stack size
 */
#define MOTOR_CONTROL_TASK_STACK			2 * configMINIMAL_STACK_SIZE // ?
#define SENSORS_CONTROL_TASK_STACK			2 * configMINIMAL_STACK_SIZE // ?
#define DEBUG_PROCESS_TASK_STACK			2 * configMINIMAL_STACK_SIZE // ?
#define WATCHDOG_TASK_STACK					2 * configMINIMAL_STACK_SIZE // ?
#define MOTOR_UART_PROCESS_RX_TASK_STACK	2 * configMINIMAL_STACK_SIZE // ?
#define MOTOR_UART_PROCESS_TX_TASK_STACK	2 * configMINIMAL_STACK_SIZE // ?

#endif /* __TASKS_STACK_AND_PRIORITY_H */
